export const planter = [
    {
        id: "monstera",
        title:"Monstera",
        imageUrl: "plante-monstera.jpg",
        price: 1150,
        shortDescription: "Medium",
        description: "Monstera er mest klasiske plante. Den har fått sin renesanse. Unngås direkte lys og ikke overvannes.",
        size: 19,
        latinName: "Monstera",
        karegori: "inneplanter"
    },
    {
        id: "fiolinfiken",
        title:"Fiolinfiken",
        imageUrl: "plante-fiolinfiken.jpg",
        price: 299,
        shortDescription: "Lett",
        description: "Fiolinfiken er en populær potteplante med lange, tynne harde blader. Den presenterer seg veldig elegant i rommet med store blader. Planten egner seg for folk som har travle dager.",
        size: 25,
        latinName: "Ficus Lyrata",
    },
    {
        id: "aloevera",
        title:"Aloe vera",
        imageUrl: "plante-aloe-vera.jpg",
        price: 169,
        shortDescription: "Lettstelt",
        description: "Denne planten har tykke grønne blader. Planeter er populær som den verdens eldste medisinplanter. Den passer perfekt som velvære og helse.",
        size: 20,
        latinName: "Aloe vera",
    },
    {
        id: "elefantore",
        title:"Elefantøre",
        imageUrl: "plante-elefantore.jpg",
        price: 45,
        shortDescription: "Vanskelig",
        description: "Elefantøre er den klassiske potteplante. Mest trendy plante i det siste. Den kan vokse til 50cm høy",
        size: 28,
        latinName: "Pilea peperomioides",
    },
    {
        id: "bonsaifiken",
        title:"Bonsaifiken",
        imageUrl: "plante-bonsaifiken.jpg",
        price: 359,
        shortDescription: "Medium",
        description: "I den kinesiske mytologien sies om at denne plante bringer rikdom.",
        size: 40,
        latinName: "Ficus Microcarpa Ginseng",
    },
    {
        id: "calathea",
        title:"Calathea",
        imageUrl: "plante-calathea.jpg",
        price: 629,
        shortDescription: "Vanskelig",
        description: "Plante som man aldri lei. Den passer perfekt for viner ettersom den har vakre blader som lyser opp vinterstid.",
        size: 80,
        latinName: "Calathea Medallion",
    },
    {
        id: "syngonium",
        title:"Syngonium",
        imageUrl: "plante-syngonium.jpg",
        price: 99,
        shortDescription: "Medium",
        description: "Når de første solstråler lyser får den vakre blomster som holder hele sommer og høst. Gjerne tørkes av støv iblant.",
        size: 60,
        latinName: "Syngonium",
    }, 
    {
        id: "bispelue",
        title:"Bispelue kaktus",
        imageUrl: "plante-bispelue-kaktus.jpg",
        price: 150,
        shortDescription: "Vanskelig",
        description: "Mest morsomste kaktus av kaktusfamilie. Blomster på toppen gjør denne planten unik.",
        size: 40,
        latinName: "Astrophytum myriostigma",
    },
    

];